/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package buckpal.kotlin.domain

import defaultActivity
import org.assertj.core.api.Assertions
import java.time.LocalDateTime
import kotlin.test.Test

class ActivityWindowTest {

    @Test
    fun calculatesStartTimestamp() {
        val window = ActivityWindow(
            defaultActivity()!!.withTimestamp(startDate()).build(),
            defaultActivity()!!.withTimestamp(inBetweenDate()).build(),
            defaultActivity()!!.withTimestamp(endDate()).build()
        )
        Assertions.assertThat(window.getStartTimestamp()).isEqualTo(startDate())
    }

    @Test
    fun calculatesEndTimestamp() {
        val window = ActivityWindow(
            defaultActivity()!!.withTimestamp(startDate()).build(),
            defaultActivity()!!.withTimestamp(inBetweenDate()).build(),
            defaultActivity()!!.withTimestamp(endDate()).build()
        )
        Assertions.assertThat(window.getEndTimestamp()).isEqualTo(endDate())
    }

    @Test
    fun calculatesBalance() {
        val account1 = AccountId(1L)
        val account2 = AccountId(2L)
        val window = ActivityWindow(
            defaultActivity()!!
                .withSourceAccount(account1)
                .withTargetAccount(account2)
                .withMoney(Money.of(999)).build(),
            defaultActivity()!!
                .withSourceAccount(account1)
                .withTargetAccount(account2)
                .withMoney(Money.of(1)).build(),
            defaultActivity()!!
                .withSourceAccount(account2)
                .withTargetAccount(account1)
                .withMoney(Money.of(500)).build()
        )
        Assertions.assertThat(window.calculateBalance(account1)).isEqualTo(Money.of(-500))
        Assertions.assertThat(window.calculateBalance(account2)).isEqualTo(Money.of(500))
    }

}

private fun startDate(): LocalDateTime {
    return LocalDateTime.of(2019, 8, 3, 0, 0)
}

private fun inBetweenDate(): LocalDateTime {
    return LocalDateTime.of(2019, 8, 4, 0, 0)
}

private fun endDate(): LocalDateTime {
    return LocalDateTime.of(2019, 8, 5, 0, 0)
}
