micronaut:
  application:
    name: buckpal-kotlin
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
datasources:
  default:
    url: jdbc:h2:mem:~/devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver
    dialect: H2
    maxPoolSize: 1
r2dbc:
  datasources:
    default:
      options:
        driver: pool
        protocol:
          h2:mem
      url: r2dbc:h2:mem:///~/devDb
      username: sa
      password: ""
